### ISSUE TITLE
赤色検出精度向上と人物検出をラズパイで実験

### ISSUE THREAD

**Issue by ShunjiHashimoto** [ShunjiHashimoto/tang#30]

**Comment by ShunjiHashimoto** [comment]
人物検出と赤検出のコードを合わせる

**Comment by ShunjiHashimoto** [comment]
合わせられたから次はラズパイで動作確認してみる

https://user-images.githubusercontent.com/63869336/131241225-98a266d9-eb4d-4e60-8ab4-2a895990eaa9.mp4

**Comment by ShunjiHashimoto** [comment]
5821e6e

**Comment by ShunjiHashimoto** [comment]
```bash
ubuntu@raspi:~$ roslaunch tang_detection tang_detection.launch 
... logging to /home/ubuntu/.ros/log/8619ec6c-08a2-11ec-a460-dca632707892/roslaunch-raspi-3750.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:39089/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11
 * /tang_detection/video_path: /home/ubuntu/catk...

NODES
  /
    tang_detection (tang_detection/redanddnn_detection.py)

auto-starting new master
process[master]: started with pid [3760]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8619ec6c-08a2-11ec-a460-dca632707892
process[rosout-1]: started with pid [3771]
started core service [/rosout]
process[tang_detection-2]: started with pid [3774]
[INFO] [1630225473.570544]: turn left
[INFO] [1630225477.496711]: turn left
[INFO] [1630225477.968514]: turn left
[INFO] [1630225478.362385]: turn left
[INFO] [1630225478.773507]: turn left
[INFO] [1630225479.168513]: turn left
[INFO] [1630225479.556759]: turn left
[INFO] [1630225480.009737]: turn left
[INFO] [1630225480.619982]: turn left
[INFO] [1630225481.014999]: turn left
[INFO] [1630225481.413263]: turn left
[INFO] [1630225481.968900]: go ahead
[INFO] [1630225482.518100]: go ahead
[INFO] [1630225482.914032]: go ahead
[INFO] [1630225483.309581]: go ahead
[INFO] [1630225483.687467]: go ahead
[INFO] [1630225484.075315]: go ahead
[INFO] [1630225484.458907]: go ahead
[INFO] [1630225484.839406]: go ahead
[INFO] [1630225485.252506]: go ahead
[INFO] [1630225485.792105]: go ahead
[INFO] [1630225486.174840]: go ahead
^C[tang_detection-2] killing on exit
^C^C^C[INFO] [1630225487.199208]: go ahead
^C^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by ShunjiHashimoto** [comment]
ラズパイで動作確認は終了、あとはロボットと繋いで動くかどうか確認する

**Comment by ShunjiHashimoto** [comment]
```bash
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py", line 264, in <module>
    detect_red.detectRed()
  File "/home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py", line 195, in detectRed
    target = self.analysisBlob(mask)
  File "/home/ubuntu/catkin_ws/src/tang/tang_detection/scripts/redanddnn_detection.py", line 156, in analysisBlob
    max_index = np.argmax(data[:, 4]) # 4列目のすべての中から最大値のindexを取得
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 1188, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
turn right
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
turn right

```

**Comment by ShunjiHashimoto** [comment]
とりあえずの対策としてargmaxがないときはtry使って分岐処理できるようにした

**Comment by ShunjiHashimoto** [comment]
動作確認はできた、ただ人物検出の処理速度が重いため、リアルタイム検出がちょっと重たい

**Comment by ShunjiHashimoto** [comment]
この問題は別のissueで建てよう
close
